### ISSUE TITLE
DOI

### ISSUE THREAD

**Issue by wby920920** [podismine/BrainMass#2]
Very rewarding work. May I ask if your article was accepted, in which journal, and if you can provide the DOI?

**Comment by wby920920** [comment]
The dataset in your study is very rich. Would it be great to be able to share it on a platform like figshare or provide a bit of processed usable data?

**Comment by podismine** [comment]
DOI: [10.1109/TMI.2024.3414476](https://doi.org/10.1109/TMI.2024.3414476)

Regarding the data, there are already some processed open-source datasets like:

abide: http://preprocessed-connectomes-project.org/abide/index.html
adhd: https://neurobureau.projects.nitrc.org/ADHD200/Introduction.html

Some other datasets are not allowing us to provide pre-processed data like UKBioBank.

Some other processed data would be shared late if possible.
